#ifndef WEBPAGE_H
#define WEBPAGE_H

// Web UI HTML page with sleek dark mode style and dynamic Fetch API updates
static const char* web_ui_html = 
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset=\"utf-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"    <title>Hydroponic Controller</title>\n"
"    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #0d0f0d;\n"
"            --surface-color: #121412;\n"
"            --surface-variant: #242623;\n"
"            --primary-color: #8eff71;\n"
"            --primary-dim: #2be800;\n"
"            --text-color: #ffffff;\n"
"            --text-dim: #a0a5a0;\n"
"            --danger-color: #ff5a5a;\n"
"        }\n"
"        * {\n"
"            box-sizing: border-box;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"        }\n"
"        body {\n"
"            font-family: 'Outfit', sans-serif;\n"
"            background-color: var(--bg-color);\n"
"            color: var(--text-color);\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            min-height: 100vh;\n"
"            padding: 20px;\n"
"        }\n"
"        .container {\n"
"            background: var(--surface-color);\n"
"            border: 1px solid var(--surface-variant);\n"
"            border-radius: 24px;\n"
"            padding: 40px 30px;\n"
"            width: 100%;\n"
"            max-width: 480px;\n"
"            box-shadow: 0 20px 40px rgba(0,0,0,0.5);\n"
"            text-align: center;\n"
"            position: relative;\n"
"            overflow: hidden;\n"
"        }\n"
"        .container::before {\n"
"            content: '';\n"
"            position: absolute;\n"
"            top: -50%;\n"
"            left: -50%;\n"
"            width: 200%;\n"
"            height: 200%;\n"
"            background: radial-gradient(circle, rgba(142,255,113,0.05) 0%, transparent 60%);\n"
"            pointer-events: none;\n"
"        }\n"
"        h1 {\n"
"            font-size: 2.2rem;\n"
"            font-weight: 800;\n"
"            margin-bottom: 8px;\n"
"            background: linear-gradient(135deg, #ffffff 30%, var(--primary-color) 100%);\n"
"            -webkit-background-clip: text;\n"
"            -webkit-text-fill-color: transparent;\n"
"        }\n"
"        .subtitle {\n"
"            font-size: 1rem;\n"
"            color: var(--text-dim);\n"
"            margin-bottom: 30px;\n"
"            font-weight: 300;\n"
"        }\n"
"        .sensor-grid {\n"
"            display: grid;\n"
"            grid-template-columns: repeat(3, 1fr);\n"
"            gap: 12px;\n"
"            margin-bottom: 30px;\n"
"        }\n"
"        .sensor-card {\n"
"            background: rgba(255, 255, 255, 0.02);\n"
"            border: 1px solid var(--surface-variant);\n"
"            border-radius: 16px;\n"
"            padding: 15px 10px;\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"        .sensor-card:hover {\n"
"            border-color: rgba(142, 255, 113, 0.3);\n"
"            background: rgba(142, 255, 113, 0.02);\n"
"        }\n"
"        .sensor-label {\n"
"            font-size: 0.75rem;\n"
"            color: var(--text-dim);\n"
"            text-transform: uppercase;\n"
"            letter-spacing: 1px;\n"
"            margin-bottom: 6px;\n"
"        }\n"
"        .sensor-value {\n"
"            font-size: 1.25rem;\n"
"            font-weight: 600;\n"
"            color: var(--primary-color);\n"
"        }\n"
"        .control-group {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 16px;\n"
"        }\n"
"        .btn {\n"
"            background: var(--surface-variant);\n"
"            border: 1px solid rgba(255,255,255,0.05);\n"
"            border-radius: 16px;\n"
"            color: var(--text-color);\n"
"            padding: 18px 24px;\n"
"            font-size: 1.1rem;\n"
"            font-weight: 600;\n"
"            cursor: pointer;\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"            outline: none;\n"
"        }\n"
"        .btn:hover {\n"
"            transform: translateY(-2px);\n"
"            border-color: rgba(255,255,255,0.1);\n"
"            box-shadow: 0 10px 20px rgba(0,0,0,0.2);\n"
"        }\n"
"        .btn.active {\n"
"            background: rgba(142, 255, 113, 0.15);\n"
"            border-color: var(--primary-color);\n"
"            color: var(--primary-color);\n"
"            box-shadow: 0 10px 25px rgba(142, 255, 113, 0.15);\n"
"        }\n"
"        .btn.active:hover {\n"
"            box-shadow: 0 12px 30px rgba(142, 255, 113, 0.25);\n"
"        }\n"
"        .btn-status {\n"
"            font-size: 0.85rem;\n"
"            text-transform: uppercase;\n"
"            letter-spacing: 1px;\n"
"            padding: 4px 10px;\n"
"            border-radius: 20px;\n"
"            background: rgba(255,255,255,0.05);\n"
"            color: var(--text-dim);\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"        .btn.active .btn-status {\n"
"            background: var(--primary-color);\n"
"            color: var(--bg-color);\n"
"            font-weight: 800;\n"
"        }\n"
"        .icon {\n"
"            margin-right: 10px;\n"
"        }\n"
"        .field {\n"
"            background: rgba(255, 255, 255, 0.02);\n"
"            border: 1px solid var(--surface-variant);\n"
"            border-radius: 16px;\n"
"            padding: 16px;\n"
"            text-align: left;\n"
"        }\n"
"        .field label {\n"
"            display: block;\n"
"            color: var(--text-dim);\n"
"            font-size: 0.8rem;\n"
"            letter-spacing: 1px;\n"
"            margin-bottom: 10px;\n"
"            text-transform: uppercase;\n"
"        }\n"
"        .field input {\n"
"            width: 100%;\n"
"            background: var(--bg-color);\n"
"            border: 1px solid rgba(255,255,255,0.08);\n"
"            border-radius: 10px;\n"
"            color: var(--primary-color);\n"
"            font: inherit;\n"
"            font-size: 1.2rem;\n"
"            font-weight: 600;\n"
"            padding: 12px;\n"
"            outline: none;\n"
"        }\n"
"        .field input:focus {\n"
"            border-color: var(--primary-color);\n"
"        }\n"
"        .section-title {\n"
"            color: var(--text-dim);\n"
"            font-size: 0.85rem;\n"
"            font-weight: 600;\n"
"            letter-spacing: 2px;\n"
"            text-transform: uppercase;\n"
"            text-align: left;\n"
"            margin-top: 10px;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>Hydroponic System</h1>\n"
"        <div class=\"subtitle\">WiFi Remote Control Panel</div>\n"
"        \n"
"        <div class=\"sensor-grid\">\n"
"            <div class=\"sensor-card\">\n"
"                <div class=\"sensor-label\">Temp</div>\n"
"                <div class=\"sensor-value\" id=\"temp-val\">-- C</div>\n"
"            </div>\n"
"            <div class=\"sensor-card\">\n"
"                <div class=\"sensor-label\">Humidity</div>\n"
"                <div class=\"sensor-value\" id=\"humidity-val\">--%</div>\n"
"            </div>\n"
"            <div class=\"sensor-card\">\n"
"                <div class=\"sensor-label\">Water</div>\n"
"                <div class=\"sensor-value\" id=\"water-val\">--%</div>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div class=\"control-group\">\n"
"            <div class=\"section-title\">Dosing Head A</div>\n"
"            <button class=\"btn\" id=\"btn-prime_a\" onclick=\"toggleDevice('prime_a')\">\n"
"                <span><span class=\"icon\">💧</span>Prime Line</span>\n"
"                <span class=\"btn-status\" id=\"status-prime_a\">OFF</span>\n"
"            </button>\n"
"            <div class=\"field\">\n"
"                <label for=\"target-ec-a\">Target EC (mS/cm)</label>\n"
"                <input id=\"target-ec-a\" type=\"number\" min=\"0\" step=\"0.1\" value=\"1.0\">\n"
"            </div>\n"
"            <button class=\"btn\" id=\"btn-target_dose_a\" onclick=\"toggleDevice('target_dose_a')\">\n"
"                <span><span class=\"icon\">🎯</span>Target Dose</span>\n"
"                <span class=\"btn-status\" id=\"status-target_dose_a\">OFF</span>\n"
"            </button>\n"
"            <button class=\"btn\" id=\"btn-shot_dose_a\" onclick=\"toggleDevice('shot_dose_a')\">\n"
"                <span><span class=\"icon\">⚡</span>Shot Dose</span>\n"
"                <span class=\"btn-status\" id=\"status-shot_dose_a\">OFF</span>\n"
"            </button>\n"
"            <div class=\"section-title\">Dosing Head B</div>\n"
"            <button class=\"btn\" id=\"btn-prime_b\" onclick=\"toggleDevice('prime_b')\">\n"
"                <span><span class=\"icon\">💧</span>Prime Line</span>\n"
"                <span class=\"btn-status\" id=\"status-prime_b\">OFF</span>\n"
"            </button>\n"
"            <div class=\"field\">\n"
"                <label for=\"target-ec-b\">Target EC (mS/cm)</label>\n"
"                <input id=\"target-ec-b\" type=\"number\" min=\"0\" step=\"0.1\" value=\"1.0\">\n"
"            </div>\n"
"            <button class=\"btn\" id=\"btn-target_dose_b\" onclick=\"toggleDevice('target_dose_b')\">\n"
"                <span><span class=\"icon\">🎯</span>Target Dose</span>\n"
"                <span class=\"btn-status\" id=\"status-target_dose_b\">OFF</span>\n"
"            </button>\n"
"            <button class=\"btn\" id=\"btn-shot_dose_b\" onclick=\"toggleDevice('shot_dose_b')\">\n"
"                <span><span class=\"icon\">⚡</span>Shot Dose</span>\n"
"                <span class=\"btn-status\" id=\"status-shot_dose_b\">OFF</span>\n"
"            </button>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        const HEADS = ['a', 'b'];\n"
"        const ROUTINES = ['prime', 'target_dose', 'shot_dose'];\n"
"        let targetEcDirty = { a: false, b: false };\n"
"\n"
"        function updateUI(status) {\n"
"            document.getElementById('temp-val').innerText = status.temp.toFixed(1) + ' C';\n"
"            document.getElementById('humidity-val').innerText = status.humidity.toFixed(1) + '%';\n"
"            document.getElementById('water-val').innerText = status.water + '%';\n"
"\n"
"            HEADS.forEach(head => {\n"
"                const ecInput = document.getElementById('target-ec-' + head);\n"
"                if (!targetEcDirty[head] && document.activeElement !== ecInput) {\n"
"                    ecInput.value = status['target_ec_' + head].toFixed(1);\n"
"                }\n"
"                ROUTINES.forEach(routine => {\n"
"                    const key = routine + '_' + head;\n"
"                    const btn = document.getElementById('btn-' + key);\n"
"                    const label = document.getElementById('status-' + key);\n"
"                    if (status[key]) {\n"
"                        btn.classList.add('active');\n"
"                        label.innerText = 'ON';\n"
"                    } else {\n"
"                        btn.classList.remove('active');\n"
"                        label.innerText = 'OFF';\n"
"                    }\n"
"                });\n"
"            });\n"
"        }\n"
"\n"
"        function fetchStatus() {\n"
"            fetch('/api/status')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    updateUI(data);\n"
"                })\n"
"                .catch(err => console.error('Error fetching status:', err));\n"
"        }\n"
"\n"
"        function toggleDevice(device) {\n"
"            let url = '/api/toggle?device=' + device;\n"
"            if (device.startsWith('target_dose_')) {\n"
"                const head = device.slice(-1);\n"
"                const targetEc = Number(document.getElementById('target-ec-' + head).value || 0).toFixed(1);\n"
"                url += '&concentration=' + encodeURIComponent(targetEc);\n"
"                targetEcDirty[head] = false;\n"
"            }\n"
"            fetch(url, { method: 'POST' })\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    updateUI(data);\n"
"                })\n"
"                .catch(err => console.error('Error toggling device:', err));\n"
"        }\n"
"\n"
"        HEADS.forEach(head => {\n"
"            document.getElementById('target-ec-' + head).addEventListener('input', () => {\n"
"                targetEcDirty[head] = true;\n"
"            });\n"
"        });\n"
"\n"
"        // Poll status every 2 seconds\n"
"        setInterval(fetchStatus, 2000);\n"
"        // Initial fetch\n"
"        fetchStatus();\n"
"    </script>\n"
"</body>\n"
"</html>\n";
#endif
